import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const plants = [
  // ── Szobanövény ─────────────────────────────────────────────────────────────
  {
    name: 'ZZ növény',
    latin_name: 'Zamioculcas zamiifolia',
    category: 'szobanövény',
    location: 'beltéri',
    price: 4990,
    sale_price: null,
    stock: 12,
    light: 'árnyék',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 45,
    max_height_cm: 100,
    current_pot_cm: 17,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.7,
    reviews_count: 134,
    description:
      'Szinte elpusztíthatatlan szobanövény, amely a sötétben és szárazságban is virágzik. Fényes, viaszos levelei dekoratívak.',
  },
  {
    name: 'Ablaklevél',
    latin_name: 'Monstera deliciosa',
    category: 'szobanövény',
    location: 'beltéri',
    price: 8990,
    sale_price: 6990,
    stock: 8,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 70,
    max_height_cm: 300,
    current_pot_cm: 21,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.8,
    reviews_count: 287,
    description:
      'Jellegzetes lyukas levelei miatt az egyik legnépszerűbb trópusi szobanövény. Párás környezetet szeret.',
  },
  {
    name: 'Hegedű-fikusz',
    latin_name: 'Ficus lyrata',
    category: 'szobanövény',
    location: 'beltéri',
    price: 14990,
    sale_price: null,
    stock: 5,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'profi',
    current_height_cm: 120,
    max_height_cm: 300,
    current_pot_cm: 26,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.3,
    reviews_count: 89,
    description:
      'Nagy, hegedű alakú levelei miatt divatos, de kényes: érzékeny a helyszínváltásra és a huzatra.',
  },
  {
    name: 'Anyós nyelve',
    latin_name: 'Sansevieria trifasciata',
    category: 'szobanövény',
    location: 'beltéri',
    price: 3490,
    sale_price: null,
    stock: 22,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 50,
    max_height_cm: 120,
    current_pot_cm: 14,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.6,
    reviews_count: 203,
    description:
      'Éjjel is oxigént termel, ezért hálószobába kiváló. Elhanyagolt körülmények közt is megél.',
  },
  {
    name: 'Békeszárny',
    latin_name: 'Spathiphyllum wallisii',
    category: 'szobanövény',
    location: 'beltéri',
    price: 3990,
    sale_price: 2990,
    stock: 15,
    light: 'alacsony',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 40,
    max_height_cm: 80,
    current_pot_cm: 14,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.5,
    reviews_count: 156,
    description:
      'Fehér virágaival és légtisztító hatásával az irodák kedvence. Félárnyékos helyeken is virágzik.',
  },
  {
    name: 'Klorofitum',
    latin_name: 'Chlorophytum comosum',
    category: 'szobanövény',
    location: 'beltéri',
    price: 1990,
    sale_price: null,
    stock: 30,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 30,
    max_height_cm: 60,
    current_pot_cm: 12,
    pet_safe: true,
    kid_safe: true,
    air_purifying: true,
    rating: 4.4,
    reviews_count: 312,
    description:
      'Háziállat- és gyerekbarát, lógó hajtásokat nevel. Kezdőknek és gyerekes háztartásokba tökéletes.',
  },
  {
    name: 'Kínai zöld',
    latin_name: 'Aglaonema commutatum',
    category: 'szobanövény',
    location: 'beltéri',
    price: 4490,
    sale_price: null,
    stock: 11,
    light: 'árnyék',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 35,
    max_height_cm: 70,
    current_pot_cm: 14,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.2,
    reviews_count: 74,
    description:
      'Tarka levelei miatt dekoratív, sötét sarkokban is megél. Mértékkel öntözve hosszú életű.',
  },
  {
    name: 'Dracéna',
    latin_name: 'Dracaena marginata',
    category: 'szobanövény',
    location: 'beltéri',
    price: 7490,
    sale_price: null,
    stock: 9,
    light: 'közepes',
    watering: 'ritka',
    difficulty: 'haladó',
    current_height_cm: 90,
    max_height_cm: 200,
    current_pot_cm: 19,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.1,
    reviews_count: 61,
    description:
      'Karcsú törzse és vörös szegélyű levelei modern enteriőrökbe illenek. Túlöntözésre érzékeny.',
  },
  // ── Pozsgás ─────────────────────────────────────────────────────────────────
  {
    name: 'Aloe',
    latin_name: 'Aloe vera',
    category: 'pozsgás',
    location: 'beltéri',
    price: 2490,
    sale_price: null,
    stock: 18,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 25,
    max_height_cm: 60,
    current_pot_cm: 12,
    pet_safe: false,
    kid_safe: true,
    air_purifying: false,
    rating: 4.5,
    reviews_count: 445,
    description:
      'Gyógyhatású nedve révén a leghasznosabb pozsgás. Napfényes ablakpárkányra való, ritkán igényel öntözést.',
  },
  {
    name: 'Pénzfa',
    latin_name: 'Crassula ovata',
    category: 'pozsgás',
    location: 'beltéri',
    price: 3990,
    sale_price: 2990,
    stock: 14,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 30,
    max_height_cm: 90,
    current_pot_cm: 14,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.3,
    reviews_count: 98,
    description:
      'Feng shui szerint szerencsét hoz. Lassan nő, de évtizedekig él, ha jól tartják.',
  },
  {
    name: 'Echeveria',
    latin_name: 'Echeveria elegans',
    category: 'pozsgás',
    location: 'beltéri',
    price: 1490,
    sale_price: null,
    stock: 25,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 10,
    max_height_cm: 20,
    current_pot_cm: 8,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.6,
    reviews_count: 187,
    description:
      'Rózsaszerű levélrózettája miatt az egyik leglátványosabb kis pozsgás. Ablakpárkányra tökéletes.',
  },
  {
    name: 'Szamárkóró',
    latin_name: 'Sedum morganianum',
    category: 'pozsgás',
    location: 'beltéri',
    price: 2990,
    sale_price: null,
    stock: 10,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 20,
    max_height_cm: 60,
    current_pot_cm: 14,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.4,
    reviews_count: 55,
    description:
      'Lógó hajtásai tele apró, könnyen leváló levelekkel. Magasból lógó cserépbe ültetve mutatós.',
  },
  // ── Kaktusz ──────────────────────────────────────────────────────────────────
  {
    name: 'Tüskéslabda kaktusz',
    latin_name: 'Mammillaria gracilis',
    category: 'kaktusz',
    location: 'beltéri',
    price: 1990,
    sale_price: null,
    stock: 20,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 12,
    max_height_cm: 20,
    current_pot_cm: 8,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.2,
    reviews_count: 67,
    description:
      'Apró fehér tüskéi és sárga virágai vannak. Gömbölyű, kompakt forma, alacsony helytartó.',
  },
  {
    name: 'Hold kaktusz',
    latin_name: 'Gymnocalycium mihanovichii',
    category: 'kaktusz',
    location: 'beltéri',
    price: 2490,
    sale_price: 1690,
    stock: 7,
    light: 'közepes',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 8,
    max_height_cm: 15,
    current_pot_cm: 8,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.0,
    reviews_count: 33,
    description:
      'Élénk vörös vagy narancssárga gömb, amely alig igényel fényt és gondozást.',
  },
  {
    name: 'Kék kaktusz',
    latin_name: 'Cereus hexagonus',
    category: 'kaktusz',
    location: 'beltéri',
    price: 5990,
    sale_price: null,
    stock: 6,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'haladó',
    current_height_cm: 60,
    max_height_cm: 600,
    current_pot_cm: 17,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.1,
    reviews_count: 28,
    description:
      'Oszlopos, kék-zöld törzse modernisztikus hatást kelt. Lassan nő, rengeteg fényt kíván.',
  },
  // ── Lógó ─────────────────────────────────────────────────────────────────────
  {
    name: 'Ördögborostyán',
    latin_name: 'Epipremnum aureum',
    category: 'lógó',
    location: 'beltéri',
    price: 2490,
    sale_price: null,
    stock: 28,
    light: 'alacsony',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 30,
    max_height_cm: 200,
    current_pot_cm: 12,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.7,
    reviews_count: 390,
    description:
      'A legrobusztusabb lógó szobanövény: szinte bármely fényviszony között megél, levegőt tisztít.',
  },
  {
    name: 'Zebranövény',
    latin_name: 'Tradescantia zebrina',
    category: 'lógó',
    location: 'beltéri',
    price: 1790,
    sale_price: null,
    stock: 16,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 20,
    max_height_cm: 100,
    current_pot_cm: 12,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.3,
    reviews_count: 112,
    description:
      'Ezüst-lila csíkos levelei rendkívül dekoratívak. Gyorsan nő, rendszeres metszést igényel.',
  },
  {
    name: 'Borostyán',
    latin_name: 'Hedera helix',
    category: 'lógó',
    location: 'mindkettő',
    price: 1990,
    sale_price: null,
    stock: 19,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 25,
    max_height_cm: 300,
    current_pot_cm: 12,
    pet_safe: false,
    kid_safe: false,
    air_purifying: true,
    rating: 4.0,
    reviews_count: 144,
    description:
      'Klasszikus lógó vagy mászó növény. Házon kívül és belül is megél, de mérgező embernek és állatnak.',
  },
  // ── Virágzó ──────────────────────────────────────────────────────────────────
  {
    name: 'Flamingóvirág',
    latin_name: 'Anthurium andraeanum',
    category: 'virágzó',
    location: 'beltéri',
    price: 4990,
    sale_price: null,
    stock: 10,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 40,
    max_height_cm: 90,
    current_pot_cm: 14,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.4,
    reviews_count: 76,
    description:
      'Fényes, viaszos vörös (vagy fehér) virága egész évben nyílhat megfelelő gondozással.',
  },
  {
    name: 'Kalanchoe',
    latin_name: 'Kalanchoe blossfeldiana',
    category: 'virágzó',
    location: 'beltéri',
    price: 1990,
    sale_price: 1490,
    stock: 24,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 20,
    max_height_cm: 40,
    current_pot_cm: 10,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.1,
    reviews_count: 234,
    description:
      'Tömött virágfejei hónapokig nyílnak. Gondozása egyszerű: erős fény, ritka öntözés.',
  },
  {
    name: 'Lepkeorchidea',
    latin_name: 'Phalaenopsis amabilis',
    category: 'virágzó',
    location: 'beltéri',
    price: 4490,
    sale_price: null,
    stock: 13,
    light: 'közepes',
    watering: 'ritka',
    difficulty: 'haladó',
    current_height_cm: 50,
    max_height_cm: 80,
    current_pot_cm: 12,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.6,
    reviews_count: 318,
    description:
      'Elegáns és kedvelt ajándék. Hetente egyszer öntözés, erős, de nem direkt fény, és hónapokig virágzik.',
  },
  {
    name: 'Kínai rózsa',
    latin_name: 'Hibiscus rosa-sinensis',
    category: 'virágzó',
    location: 'beltéri',
    price: 3990,
    sale_price: null,
    stock: 7,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 45,
    max_height_cm: 200,
    current_pot_cm: 17,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 3.9,
    reviews_count: 42,
    description:
      'Látványos, trombitaszerű virágai naponta nyílnak és hervadnak. Sok fényt és rendszeres öntözést kíván.',
  },
  // ── Fűszer ───────────────────────────────────────────────────────────────────
  {
    name: 'Bazsalikom',
    latin_name: 'Ocimum basilicum',
    category: 'fűszer',
    location: 'mindkettő',
    price: 890,
    sale_price: null,
    stock: 40,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'kezdő',
    current_height_cm: 20,
    max_height_cm: 50,
    current_pot_cm: 10,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.3,
    reviews_count: 521,
    description:
      'Nélkülözhetetlen konyhai fűszer, konyhapárkányra ideális. Rendszeres csípéssel bokros lesz.',
  },
  {
    name: 'Borsmenta',
    latin_name: 'Mentha x piperita',
    category: 'fűszer',
    location: 'mindkettő',
    price: 990,
    sale_price: null,
    stock: 35,
    light: 'közepes',
    watering: 'gyakori',
    difficulty: 'kezdő',
    current_height_cm: 25,
    max_height_cm: 60,
    current_pot_cm: 12,
    pet_safe: false,
    kid_safe: true,
    air_purifying: false,
    rating: 4.2,
    reviews_count: 287,
    description:
      'Frissítő illatú, teába és ételekbe egyaránt használható. Gyorsan terjed, érdemes külön cserépben tartani.',
  },
  {
    name: 'Rozmaring',
    latin_name: 'Rosmarinus officinalis',
    category: 'fűszer',
    location: 'mindkettő',
    price: 1490,
    sale_price: null,
    stock: 20,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'haladó',
    current_height_cm: 30,
    max_height_cm: 150,
    current_pot_cm: 14,
    pet_safe: false,
    kid_safe: true,
    air_purifying: false,
    rating: 4.0,
    reviews_count: 163,
    description:
      'Mediterrán fűszer, amely teli napot és laza, jól vízáteresztő talajt igényel. Télen hidegebb helyet szeret.',
  },
  // ── Fa-cserje ────────────────────────────────────────────────────────────────
  {
    name: 'Puszpáng',
    latin_name: 'Buxus sempervirens',
    category: 'fa-cserje',
    location: 'kültéri',
    price: 2990,
    sale_price: null,
    stock: 15,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 40,
    max_height_cm: 150,
    current_pot_cm: 17,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.0,
    reviews_count: 54,
    description:
      'Örökzöld sövény- vagy topiar-növény. Lassú növekedésű, de jól formálható és fagyálló.',
  },
  {
    name: 'Hortenzia',
    latin_name: 'Hydrangea macrophylla',
    category: 'fa-cserje',
    location: 'kültéri',
    price: 4490,
    sale_price: 3490,
    stock: 11,
    light: 'közepes',
    watering: 'gyakori',
    difficulty: 'haladó',
    current_height_cm: 50,
    max_height_cm: 200,
    current_pot_cm: 19,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.5,
    reviews_count: 189,
    description:
      'Masszív virágbugái kék, lila vagy rózsaszín árnyalatban pompáznak. Sok vizet igényel, félárnyékot szeret.',
  },
  {
    name: 'Kerti azálea',
    latin_name: 'Rhododendron obtusum',
    category: 'fa-cserje',
    location: 'kültéri',
    price: 3990,
    sale_price: null,
    stock: 8,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 40,
    max_height_cm: 150,
    current_pot_cm: 17,
    pet_safe: false,
    kid_safe: false,
    air_purifying: false,
    rating: 4.2,
    reviews_count: 77,
    description:
      'Tavasszal bomba virágzású cserjék. Savanykás talajt és lágy vizet igényelnek.',
  },
  // ── Kerti ────────────────────────────────────────────────────────────────────
  {
    name: 'Levendula',
    latin_name: 'Lavandula angustifolia',
    category: 'kerti',
    location: 'kültéri',
    price: 1990,
    sale_price: null,
    stock: 25,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    current_height_cm: 30,
    max_height_cm: 80,
    current_pot_cm: 14,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.7,
    reviews_count: 403,
    description:
      'Illatos lila virágai relaxáló illatot árasztanak. Teli nap és jó vízelvezető talaj kell hozzá.',
  },
  {
    name: 'Csipkerózsa',
    latin_name: 'Rosa canina',
    category: 'kerti',
    location: 'kültéri',
    price: 3490,
    sale_price: null,
    stock: 10,
    light: 'direkt nap',
    watering: 'közepes',
    difficulty: 'haladó',
    current_height_cm: 60,
    max_height_cm: 300,
    current_pot_cm: 19,
    pet_safe: true,
    kid_safe: true,
    air_purifying: false,
    rating: 4.1,
    reviews_count: 67,
    description:
      'Vad rózsa, amely az őszi terméseiről (csipkebogyó) is értékes. Fagyálló és könnyen tartható.',
  },
];

async function main() {
  console.log(`Seed: ${plants.length} növény betöltése...`);
  await prisma.product.deleteMany();
  const result = await prisma.product.createMany({
    data: plants.map((p) => ({
      ...p,
      price: p.price,
      sale_price: p.sale_price ?? null,
    })),
  });
  console.log(`Kész: ${result.count} rekord létrehozva.`);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
